### ISSUE TITLE
配置不成功啊

### ISSUE THREAD

**Issue by ifooth** [ichuan/djblog#1]
Win7/Python2.73/Django1.41 
1. syncdb  
             显示找不到djblog.blog 我改成blog 通过
2. runserver 81 
              ImportError: No module named djblog.urls
3. 下面懒的调试了

**Comment by ichuan** [comment]
简单解决方法：把代码所在目录名改成 `djblog` 
或者修改 `settings.py`，把 `TEMPLATE_CONTEXT_PROCESSORS`、`ROOT_URLCONF` 和 `INSTALLED_APPS` 里的 `djblog` 替换成所在的目录名称

**Comment by ifooth** [comment]
成了但是如果只用runserver  不用nginx配置 是不是admin 会显示不正常？

**Comment by ichuan** [comment]
`runserver`  和用 `nginx` 做前端下管理界面都正常。你试试

**Comment by ifooth** [comment]
href="admin/css/base.css" href="admin/css/login.css 这些链接是404 not found 所以界面是不能正常显示的

**Comment by ichuan** [comment]
你改了 `settings.py` 里的 `ADMIN_MEDIA_PREFIX` 吧？正常应该是 `ADMIN_MEDIA_PREFIX = '/static/admin/'`，我刚才测试了下，管理界面显示没问题，不清楚你改了什么。

**Comment by ichuan** [comment]
fixed in issue #2
