### ISSUE TITLE
请问：ImportError: No module named djblog

### ISSUE THREAD

**Issue by wayne0x** [ichuan/djblog#9]
你好，请问一下，在执行python manage.py syncdb这个时候出现的错误。
本地环境。python2.7.8,mysql:5.6.17.
刚把项目下载之后。
执行python manage.py syncdb。报错ImportError: cannot import name execute_manager，我在django\core\management__init__.py添加了execute_manager
执行python manage.py syncdb。报错NameError: global name 'setup_environ' is not defined，我在django添加了setup_environ

再执行python manage.py syncdb 就出现ImportError: No module named djblog这个错误了。

小白一枚，请大神指教。谢谢

**Comment by wayne0x** [comment]
D:\PRO\python\djblog-master\djblog-master>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_manager(settings)
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line
394, in execute_manager
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line
354, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 116, in creat
e
    mod = import_module(mod_path)
  File "C:\Python27\lib\importlib__init__.py", line 37, in import_module
    **import**(name)
ImportError: No module named djblog

**Comment by yuealves** [comment]
django版本不对，建议你用virtualenv创建一个合适的环境

**Comment by ichuan** [comment]
@way85  不用修改 django 代码，问题不在 django。

之前的问题应该是环境没有配置好。djblog 依赖 django 1.3.1（新版本没有测试过）和 markdown，像 @yuealves 说的，可以用 virtualenv 来搭环境：

``` bash
sudo apt-get install -y python-pip
sudo pip install virtualenv
# 创建虚拟环境
mkdir -p ~/envs && virtualenv ~/envs/djblog
# 进入虚拟环境
source ~/envs/djblog/bin/activate
# 安装依赖
pip install -r requirements.txt
# 同步数据库
python manage.py syncdb
# ...
# 退出虚拟环境
deactivate
```

后面的 `No module named djblog` 问题在于，放代码的文件夹必须命名为 `djblog`，sorry 这是在代码里写死的，你可以在 `settings.py` 中替换掉。

另外建议修改 `local_settings.py` 把数据库修改为 sqlite3 使用，问题更少些。

**Comment by wayne0x** [comment]
非常感谢解答，我会尝试弄一下，有问题会再麻烦你，感谢
